"""added storage_bytes, over_quota to projects table

Revision ID: 0afbe7c643c9
Revises: 1cc543492d0f
Create Date: 2026-08-14 08:47:29.715957

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0afbe7c643c9"
down_revision: str | Sequence[str] | None = "1cc543492d0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("storage_bytes", sa.BigInteger(), server_default="0", nullable=False)
    )
    op.add_column(
        "projects", sa.Column("over_quota", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "over_quota")
    op.drop_column("projects", "storage_bytes")
    # ### end Alembic commands ###
